config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :fammembers do
    resources :patients, only: [:new, :create, :show, :edit, :delete]
    resources :reviews
  end


resources :reviews

  resources :caregivers do
    resources :transactions
    resources :reviews
  end

  get 'edit_transaction' => 'transactions#edit'
  put 'edit_transaction' => 'transactions#update'


  # resources :transactions
  resources :searches


  root 'home#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/caregiver.rb
class Caregiver < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :languages
  has_and_belongs_to_many :specialties
  after_initialize :defaultVal

  validates :gender, presence: true
  validates :yearsofexperience, presence: true


  def upload_file
  end

  def defaultVal
    self.certification = false if self.certification.nil?
  end
end

app/models/fammember.rb
class Fammember < ApplicationRecord
  belongs_to :user
  has_many :patients
end

app/models/language.rb
class Language < ApplicationRecord
  has_and_belongs_to_many :caregivers

  validates :sglang, uniqueness: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :fammember

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :owner, foreign_key: "transaction_id", class_name: "Transaction"
end

app/models/search.rb
class Search < ApplicationRecord

    def search_caregivers_attributes
      caregivers = Caregiver.all
      caregivers = caregivers.where("yearsofexperience >= ?", yearsofexperience) if yearsofexperience.present?
      caregivers = caregivers.where("lower(gender) LIKE ?", gender.downcase) if gender.present?
      if self.specialties.present?
        arr = JSON.parse(self.specialties)
        p 'arr contains ...'
        puts arr.length
        if arr.length > 1 # cos there's alaways a blank string being submitted.
          caregiversSpecialty = CaregiversSpecialties.where(specialty_id: arr.map {|x|  x.to_i}).pluck(:caregiver_id)
          p 'caregivers located...? '
          p caregiversSpecialty
          caregivers = caregivers.where(id: caregiversSpecialty)
        end
      end
      if self.languages.present?
        arr = JSON.parse(self.languages)
        if arr.length > 1  # cos there's alaways a blank string being submitted.
          caregiversLanguages = CaregiversLanguages.where(language_id: arr.map {|x|  x.to_i}).pluck(:caregiver_id)
          p 'caregivers located...? '
          p caregiversLanguages
          caregivers = caregivers.where(id: caregiversLanguages)
        end
      end

      return caregivers
    end

end

app/models/specialty.rb
class Specialty < ApplicationRecord
  has_and_belongs_to_many :caregivers

  validates :ability, uniqueness: true


end

app/models/transaction.rb
class Transaction < ApplicationRecord

  belongs_to :user
  belongs_to :caregiver
  has_many :reviews
  belongs_to :patient
  
end

app/models/user.rb
class User < ApplicationRecord
  has_one :fammember, dependent: :destroy
  has_one :caregiver, dependent: :destroy
  has_many :reviews


  before_save {self.email = email.downcase}

  validates :email,
  presence: true,
  uniqueness: {case_sensitive: false},
  format: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :password, length: {in: 8..72}, on: :create

  validates :contact, length: {is: 8},
  presence: true

  has_secure_password

  def self.find_and_authenticate(params)
    User.find_by_email(params[:email]).try(:authenticate, params[:password])
  end
end

app/controllers/caregivers_controller.rb
class CaregiversController < ApplicationController
  before_action :set_caregiver, only: [:show, :edit, :update, :destroy]
  before_action :is_authenticated, only: [:search, :update, :delete, :edit, :show ]

  def index
    @caregivers = Caregiver.all
  end

  def search
    @caregivers = Caregiver.search(params[:search])
  end

  def show
      if current_user.usertype === "Caregiver"
      #  @caregiver = Caregiver.find_by(user_id: params[:id])
      #  @review = Review.where(user_id: current_user.id)
      #  p '*' * 100
      # #  p Transaction.
      # #  p @transaction_caregiver = Transaction.find_by(user_id: current_user.id).caregiver_id
      # #  p @caregivers = Caregiver.find_by(id: @transaction_caregiver).user_id
      # #  p @caregivers_name = User.find_by(id: @caregivers).first_name

        p "T" *100
        p params
       @caregiver = Caregiver.find_by!(user_id: params[:id])
       @review = Review.where(user_id: current_user.id)
       p '*' * 100
      @transaction = Transaction.where(caregiver_id: @caregiver.id)
      p @transaction
      #  @caregivers = Caregiver.find_by!(id: @transaction)
      #  @caregivers_name = User.find_by!(id: @caregivers)

       p '*' * 100
     elsif current_user.usertype === "Fammember"
       @caregiver = Caregiver.find_by(id: params[:id])
    end
  end

  def new
    @user = User.new
    @caregiver = Caregiver.new
  end

  def create
    @user = User.new(user_params)
      if @user.save
        @caregiver = Caregiver.new(caregiver_params)
        @caregiver.user_id = @user.id
            upload
      if @caregiver.save
        flash[:success] = "Your profile has been sucessfully created"
        redirect_to login_path
      else
        @user.destroy if @user.save
        flash[:failure] = "Error..."
        redirect_to :back
      end
    end
  end

  def edit
  end

  def update
    upload
    @user = User.update(user_params)
    @caregiver = Caregiver.update(caregiver_params)
    redirect_to caregiver_path
  end

  def destroy
    # Cloudinary::Api.delete_resources(Caregiver.user_id(params[@user.id]).photo])
    @user.destroy
    flash[:success] = "account has been successfully deleted."
    redirect_to '/'
  end

  private

  def upload
   if params[:details][:photo].present?
     if @caregiver.valid?
       uploaded_file = params[:details][:photo].path
       cloudinary_file = Cloudinary::Uploader.upload(uploaded_file)
       @caregiver.photo = cloudinary_file['public_id']
     end
     params[:details].delete :photo
   end
end

  def set_caregiver
    @user = User.find(params[:id])

  end

  def user_params
    params.require(:details).permit(:first_name, :last_name, :email, :password, :contact, :usertype)
  end

  def caregiver_params
    params.require(:details).permit(:gender, :certification, :yearsofexperience, :experiencedescription, :photo, :language_ids => [], :specialty_ids => [])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caregivers_helper.rb
module CaregiversHelper
end

app/helpers/careseekers_helper.rb
module CareseekersHelper
end

app/helpers/fammembers_helper.rb
module FammembersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/caregivers/_form.html.erb
<%= bootstrap_form_for(:details, url: caregivers_path, html: { method: :post }) do |f| %>

  <div>
    <%= f.text_field :first_name %>
  </div>

  <div>
    <%= f.text_field :last_name %>
  </div>

  <div>
    <%= f.email_field :email %>
  </div>

  <div>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.text_field :contact %>
  </div>

  <div>
    <%= f.text_field :usertype, value: 'Caregiver', :readonly => 'readonly' %>
  </div>

  <div>
    <%= f.text_field :gender %>
  </div>

  <div>
    <%= f.collection_radio_buttons :certification , [[true, 'True'] ,[false, 'False']], :first, :last,  {:item_wrapper_class => 'inline'}  %>
  </div>

  <div>
    <%= f.collection_check_boxes(:language_ids, Language.all, :id, :sglang,  {:label => 'Language'}) %>
  </div>

  <div>
    <%= f.collection_check_boxes(:specialty_ids, Specialty.all, :id, :ability, {:label => 'Specialty'}) %>
  </div>

  <div>
    <%= f.text_field :yearsofexperience %>
  </div>

  <div>
    <%= f.text_area :experiencedescription %>
  </div>

  <div>
    <%= f.file_field :photo %>
  </div>

  <div>
    <%= f.submit "Register" %>
  </div>
<% end %>

app/views/caregivers/_test.html.erb
<h1>All our caregivers</h1>
<table>
  <thead>
    <tr>
      <th class="col-xs-2">ID</th>
      <th class="col-xs-2">User ID</th>
      <th class="col-xs-2">Email</th>
      <th class="col-xs-2">Gender</th>
      <th class="col-xs-2">Years of experience</th>
      <th class="col-xs-2">Expertise</th>
      <th class="col-xs-2">Experience description</th>
      <th class="col-xs-2">Languages Spoken</th>
      <th class="col-xs-2">Book Now</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @caregivers.each do |c| %>
        <td><%= c.id %></td>
        <td><%= c.user_id %></td>
        <td><%= User.find_by(id: c.user_id).email %></td>
        <td><%= c.gender %></td>
        <td><%= c.yearsofexperience %></td>
        <td><%= c.specialties %></td>
        <td><%= c.experiencedescription %></td>
        <td><%= c.languages %></td>
        <td><%= link_to "Book Now", new_caregiver_transaction_path(c.id) %></td>
    </tr>
      <% end %>
  </tbody>
</table>

app/views/caregivers/index.html.erb
<h1>Hi there caregiver</h1>
<center><button type = "button" class = "btn btn-default"><%= link_to 'Join Us', new_caregiver_path %></button></center>

<p>
</p>
<p></p>
<p>If you're looking to make a difference to patients, Silver Home Care gives you the freedom to control when you work at where you want.</p>

<p>Click the join button now find out more.</p>

<br>

<p>Interested to make a career switch to become a full-time or part-time caregiver? Check out <a href="https://www.moh.gov.sg/content/moh_web/healthprofessionalsportal/nurses/career_practice/nursing_trainingandeducation.html">here</a></p>

app/views/caregivers/new.html.erb
<h1>Caregiver Sign Up Page</h1>
<%= render 'form' %>

<%= link_to 'Back', caregivers_path %>

app/views/caregivers/show.html.erb
<h1>Welcome <%=current_user.first_name%></h1>

<div class="container">

<center><h4>Your bookings</h4></center>
<div class="row">
<table class="table table-bordered">
<thead>
  <tr>
    <th class="col-xs-2">Name of caregiver</th>
    <th class="col-xs-2">Family Member</th>
    <th class="col-xs-2">Start date of booking</th>
    <th class="col-xs-2">Status</th>
    <th class="col-xs-2">Functions</th>
    <th class="col-xs-2">Reviews</th>
  </tr>
</thead>

<tbody>
  <tr>
    <% if current_user.usertype === "Caregiver" %>
    <% @transaction.each do |t| %>
    <td><%= User.find_by(id: params[:id]).first_name %> <%= User.find_by(id: params[:id]).last_name %></td>
    <td><%= User.find_by(id: t.user_id).first_name %> <%= User.find_by(id: t.user_id).last_name %></td>
    <td><%= t.start_date %></td>
    <td>
      <ul>
        <li>Pending: <%= t.pending %></li>
        <li>Approved: <%= t.approved %></li>
      </ul>
    </td>
    <td><%= link_to 'Edit', edit_caregiver_transaction_path(current_user.id, t.id) %></td>
    <td>  <% if t.approved == true %>
      <%=link_to 'Write review', new_caregiver_review_path(t.caregiver_id)%>
    <% else %>
        Unavailable
    <% end %>
    </td>

  </tr>
    <% end %>
</tbody>
</table>

<% end %>
</div>

<br>
<br>
<center><h4>Your review</h4></center>
<div class="row">
<table class="table table-bordered">
  <thead>
    <tr>
      <th class="col-xs-1">Reviewed on</th>
      <th class="col-xs-1">Review date</th>
      <th class="col-xs-2">Rating</th>
      <th class="col-xs-4">Comment</th>
      <th class="col-xs-2">Functions</th>
    </tr>
  </thead>

  <tbody>

    <% @review.each do |review| %>
      <tr>
          <% @test = Transaction.find_by(id: review.transaction_id).user_id %>
        <td><%= User.find_by(id: @test).first_name %> <%= User.find_by(id: @test).last_name %></td>
        <td><%= review.created_at %></td>
        <td><div class = "star-rating" data-score= <%= review.rating %></div></td>
        <td><%= review.comment %></td>
        <td><%= link_to 'Edit', edit_caregiver_review_path(review.user_id,review.id) %>
      <%= link_to 'Destroy', caregiver_review_path(review.user_id,review.id) , method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

<br>
<br>

<center><h4>Your Profile</h4></center>
  <div class="row">
<table class="table table-bordered">
  <thead>
    <tr>
      <th class="col-xs-2">Name</th>
      <th class="col-xs-1">Gender</th>
      <th class="col-xs-1">Years of experience</th>
      <th class="col-xs-3">Expertise</th>
      <th class="col-xs-4">Experience description</th>
      <th class="col-xs-3">Languages Spoken</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <% if current_user.usertype === "Caregiver" %>
      <td><%= User.find_by(id: params[:id]).first_name %> <%= User.find_by(id: params[:id]).last_name %></td>
      <td><%= @caregiver.gender %></td>
      <td><%= @caregiver.yearsofexperience %></td>
      <td>
        <ul><% @caregiver.specialties.each do |x| %>
          <li><%=x.ability%></li>
          <% end %>
        </ul>
      </td>
      <td><%= @caregiver.experiencedescription %></td>
      <td>
        <ul><% @caregiver.languages.each do |x| %>
          <li><%= x.sglang %></li>
          <% end %>
        </ul>
      </td>

      <% elsif current_user.usertype === "Fammember" %>
      <%= User.find_by(id: Caregiver.find_by(id: params[:id]).user_id).email %>
      <td><%= User.find_by(id: Caregiver.find_by(id: params[:id]).user_id).first_name %></td>
      <td><%= @caregiver.gender %></td>
      <td><%= @caregiver.yearsofexperience %></td>
      <td><%= @caregiver.specialties %></td>
      <td><%= @caregiver.experiencedescription %></td>
      <td><%= @caregiver.languages %></td>
      <td><%= link_to "Book Now", new_caregiver_transaction_path(@caregiver) %></td>
      <% end %>
    </tr>
  </tbody>
</table>

</div>


</div>


<%= link_to 'New Review', new_caregiver_review_path(@user) %>


<script>
  $('.star-rating').raty({
    path: '/assets',
    readOnly: true,
    score: function() {
        return $(this).attr('data-score');
    }
  });
</script>