config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :fammembers do
    resources :patients, only: [:new, :create, :show, :edit, :delete]
    resources :reviews
  end


resources :reviews

  resources :caregivers do
    resources :transactions
    resources :reviews
  end

  get 'edit_transaction' => 'transactions#edit'
  put 'edit_transaction' => 'transactions#update'


  # resources :transactions
  resources :searches


  root 'home#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/caregiver.rb
class Caregiver < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :languages
  has_and_belongs_to_many :specialties
  after_initialize :defaultVal

  validates :gender, presence: true
  validates :yearsofexperience, presence: true


  def upload_file
  end

  def defaultVal
    self.certification = false if self.certification.nil?
  end
end

app/models/fammember.rb
class Fammember < ApplicationRecord
  belongs_to :user
  has_many :patients
end

app/models/language.rb
class Language < ApplicationRecord
  has_and_belongs_to_many :caregivers

  validates :sglang, uniqueness: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :fammember

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :owner, foreign_key: "transaction_id", class_name: "Transaction"
end

app/models/search.rb
class Search < ApplicationRecord

    def search_caregivers_attributes
      caregivers = Caregiver.all
      caregivers = caregivers.where("yearsofexperience >= ?", yearsofexperience) if yearsofexperience.present?
      caregivers = caregivers.where("lower(gender) LIKE ?", gender.downcase) if gender.present?
      if self.specialties.present?
        arr = JSON.parse(self.specialties)
        p 'arr contains ...'
        puts arr.length
        if arr.length > 1 # cos there's alaways a blank string being submitted.
          caregiversSpecialty = CaregiversSpecialties.where(specialty_id: arr.map {|x|  x.to_i}).pluck(:caregiver_id)
          p 'caregivers located...? '
          p caregiversSpecialty
          caregivers = caregivers.where(id: caregiversSpecialty)
        end
      end
      if self.languages.present?
        arr = JSON.parse(self.languages)
        if arr.length > 1  # cos there's alaways a blank string being submitted.
          caregiversLanguages = CaregiversLanguages.where(language_id: arr.map {|x|  x.to_i}).pluck(:caregiver_id)
          p 'caregivers located...? '
          p caregiversLanguages
          caregivers = caregivers.where(id: caregiversLanguages)
        end
      end

      return caregivers
    end

end

app/models/specialty.rb
class Specialty < ApplicationRecord
  has_and_belongs_to_many :caregivers

  validates :ability, uniqueness: true


end

app/models/transaction.rb
class Transaction < ApplicationRecord

  belongs_to :user
  belongs_to :caregiver
  has_many :reviews
  belongs_to :patient
  
end

app/models/user.rb
class User < ApplicationRecord
  has_one :fammember, dependent: :destroy
  has_one :caregiver, dependent: :destroy
  has_many :reviews


  before_save {self.email = email.downcase}

  validates :email,
  presence: true,
  uniqueness: {case_sensitive: false},
  format: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :password, length: {in: 8..72}, on: :create

  validates :contact, length: {is: 8},
  presence: true

  has_secure_password

  def self.find_and_authenticate(params)
    User.find_by_email(params[:email]).try(:authenticate, params[:password])
  end
end

app/controllers/fammembers_controller.rb
class FammembersController < ApplicationController
  before_action :set_fammember, only: [:show, :edit, :update, :destroy]
  before_action :is_authenticated, only: [:update, :destroy, :edit, :show ]
  before_action :is_authenticated_fammember, only: [:update, :destroy, :edit, :show ]


  def index
  end

  def show
    @review = Review.where(user_id: @user.id)
    @fammember = Fammember.find_by(user_id: params[:id])
    p '#' * 50
    puts @fammember.inspect

    if Patient.where(fammember_id: Fammember.find_by(user_id: current_user.id)) != nil
    @patient = Patient.where(fammember_id: @fammember)
    end
    if Transaction.find_by(user_id: current_user.id) != nil
    @transaction = Transaction.where(user_id: current_user.id)
    @transaction_caregiver = Transaction.find_by(user_id: current_user.id).caregiver_id
    @transaction_patient = Transaction.find_by(user_id: current_user.id).patient_id
    @caregivers = Caregiver.find_by(id: @transaction_caregiver).user_id

    @caregivers_name = User.find_by(id: @caregivers).first_name

    @caregivers_whole = User.find_by(id: @caregivers)
    end
  end

  def new
    @user = User.new
    @fammember = Fammember.new
  end

  def create
    @user = User.new(fammember_params)
      if @user.save
        UserMailer.welcome_email(@user).deliver
        @fammember = Fammember.new
        @fammember.user_id = @user.id
        if @fammember.save
          flash[:success] = "Your profile has been sucessfully created"
          redirect_to login_path
        end
      else
        flash[:failure] = "Error..."
        redirect_to :back
    end
  end

  def edit
  end

  def update
    @user = User.update(fammember_params)
    redirect_to fammember_path
  end

  def destroy
    @user.destroy
    flash[:success] = "account has been successfully deleted."
    redirect_to '/'
  end

  private

  def set_fammember
    @user = User.find(params[:id])
  end

  def fammember_params
    params.require(:fammembers).permit(:first_name, :last_name, :contact, :email, :password, :usertype)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caregivers_helper.rb
module CaregiversHelper
end

app/helpers/careseekers_helper.rb
module CareseekersHelper
end

app/helpers/fammembers_helper.rb
module FammembersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fammembers/_form.html.erb
<%= bootstrap_form_for(:fammembers, url: fammembers_path, html: { method: :post }) do |f| %>

  <div>
    <%= f.text_field :first_name %>
  </div>

  <div>
    <%= f.text_field :last_name %>
  </div>

  <div>
    <%= f.text_field :email %>
  </div>

  <div>
    <%= f.password_field :password %>
  </div>

  <div>
    <%= f.text_field :contact %>
  </div>

  <div>
    <%= f.text_field :usertype, value: 'Fammember', :readonly => 'readonly' %>
  </div>

  <div>
    <%= f.submit "Register" %>
  </div>
<% end %>

app/views/fammembers/index.html.erb
<h1>Hi there, welcome to Silver Home Care App</h1>

app/views/fammembers/new.html.erb
<h1>Sign Up to use our services</h1>

<%= render 'form'%>

<br>

<button type = "button" class = "btn btn-default"><%= link_to 'Back', fammembers_path %></button>

app/views/fammembers/show.html.erb
<h1>Welcome back <%= @user.first_name %></h1>

<li><%= link_to "Search", new_search_path %></li>
<li><%= link_to "New patient", new_fammember_patient_path(@user) %></li>

<br>
<br>
<center><h4>List of Patients</h4></center>
<div class="container">

<div class="row">
<table class="table table-bordered">
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Address</th>
      <th>Gender</th>
      <th>Frequency</th>
      <th>Condition Description</th>
    </tr>
  </thead>

  <tbody>
    <% @patient.each do |patient| %>
      <tr>
        <td class="col-xs-2"><%= patient.first_name %></td>
        <td class="col-xs-2"><%= patient.last_name %></td>
        <td class="col-xs-2"><%= patient.address %></td>
        <td class="col-xs-2"><%= patient.gender %></td>
        <td class="col-xs-2"><%= patient.frequency %></td>
        <td class="col-xs-2"><%= patient.condition_description %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>
<br>
<center><h4>Your Bookings</h4></center>
<div class="row">
<table class="table table-bordered">
<thead>
  <tr>
    <th class="col-xs-2">Name of caregiver</th>
    <th class="col-xs-2">For patient</th>
    <th class="col-xs-2">Start date of booking</th>
    <th class="col-xs-2">Status</th>
    <th class="col-xs-2">Functions</th>
    <th class="col-xs-2">Reviews</th>
  </tr>
</thead>

<tbody>
  <tr>
    <% if @transaction.present? %>
    <%= @transaction.each do |t| %>
    <td><%= User.find_by(id: @caregivers).first_name %> <%= User.find_by(id: @caregivers).last_name %></td>
    <% @patient.each do |p| %>
    <td><%= p.first_name %> <%= p.last_name %></td>
    <td><%= t.start_date %></td>
    <td>
      <ul>
        <li>Pending: <%= t.pending %></li>
        <li>Approved: <%= t.approved %></li>
      </ul>
    </td>
    <td><%= link_to 'Edit', edit_transaction_path(t.id) %></td>
    <td>  <% if t.approved == true %>
      <%=link_to 'Write review', new_review_path%>
    <% else %>
        Unavailable
    <% end %>

    </td>

  </tr>
  <% end %>
  <% end %>
  <% end %>
</tbody>
</table>

</div>


<br>
<br>
<center><h4>Review</h4></center>
<div class="row">
<table class="table table-bordered">
  <thead>
    <tr>
      <th class="col-xs-1">Reviewed on</th>
      <th class="col-xs-1">Review date</th>
      <th class="col-xs-2">Rating</th>
      <th class="col-xs-4">Comment</th>
      <th class="col-xs-2">Functions</th>
    </tr>
  </thead>

  <tbody>


    <% @review.each do |review| %>
      <tr>
        <td><%= @caregivers_whole.first_name %> <%= @caregivers_whole.last_name %></td>
        <td><%= review.created_at %></td>
        <td><div class = "star-rating" data-score= <%= review.rating %></div></td>
        <td><%= review.comment %></td>
        <td><%= link_to 'Edit', edit_fammember_review_path(review.user_id,review.id) %>
      <%= link_to 'Destroy', fammember_review_path(review.user_id,review.id) , method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

<%= link_to 'New Review', new_fammember_review_path(@user) %>


<script>
  $('.star-rating').raty({
    path: '/assets',
    readOnly: true,
    score: function() {
        return $(this).attr('data-score');
    }
  });
</script>