config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :fammembers do
    resources :patients, only: [:new, :create, :show, :edit, :delete]
    resources :reviews
  end


resources :reviews

  resources :caregivers do
    resources :transactions
    resources :reviews
  end

  get 'edit_transaction' => 'transactions#edit'
  put 'edit_transaction' => 'transactions#update'


  # resources :transactions
  resources :searches


  root 'home#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/caregiver.rb
class Caregiver < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :languages
  has_and_belongs_to_many :specialties
  after_initialize :defaultVal

  validates :gender, presence: true
  validates :yearsofexperience, presence: true


  def upload_file
  end

  def defaultVal
    self.certification = false if self.certification.nil?
  end
end

app/models/fammember.rb
class Fammember < ApplicationRecord
  belongs_to :user
  has_many :patients
end

app/models/language.rb
class Language < ApplicationRecord
  has_and_belongs_to_many :caregivers

  validates :sglang, uniqueness: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :fammember

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :owner, foreign_key: "transaction_id", class_name: "Transaction"
end

app/models/search.rb
class Search < ApplicationRecord

    def search_caregivers_attributes
      caregivers = Caregiver.all
      caregivers = caregivers.where("yearsofexperience >= ?", yearsofexperience) if yearsofexperience.present?
      caregivers = caregivers.where("lower(gender) LIKE ?", gender.downcase) if gender.present?
      if self.specialties.present?
        arr = JSON.parse(self.specialties)
        p 'arr contains ...'
        puts arr.length
        if arr.length > 1 # cos there's alaways a blank string being submitted.
          caregiversSpecialty = CaregiversSpecialties.where(specialty_id: arr.map {|x|  x.to_i}).pluck(:caregiver_id)
          p 'caregivers located...? '
          p caregiversSpecialty
          caregivers = caregivers.where(id: caregiversSpecialty)
        end
      end
      if self.languages.present?
        arr = JSON.parse(self.languages)
        if arr.length > 1  # cos there's alaways a blank string being submitted.
          caregiversLanguages = CaregiversLanguages.where(language_id: arr.map {|x|  x.to_i}).pluck(:caregiver_id)
          p 'caregivers located...? '
          p caregiversLanguages
          caregivers = caregivers.where(id: caregiversLanguages)
        end
      end

      return caregivers
    end

end

app/models/specialty.rb
class Specialty < ApplicationRecord
  has_and_belongs_to_many :caregivers

  validates :ability, uniqueness: true


end

app/models/transaction.rb
class Transaction < ApplicationRecord

  belongs_to :user
  belongs_to :caregiver
  has_many :reviews
  belongs_to :patient
  
end

app/models/user.rb
class User < ApplicationRecord
  has_one :fammember, dependent: :destroy
  has_one :caregiver, dependent: :destroy
  has_many :reviews


  before_save {self.email = email.downcase}

  validates :email,
  presence: true,
  uniqueness: {case_sensitive: false},
  format: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :password, length: {in: 8..72}, on: :create

  validates :contact, length: {is: 8},
  presence: true

  has_secure_password

  def self.find_and_authenticate(params)
    User.find_by_email(params[:email]).try(:authenticate, params[:password])
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  before_action :set_caregiver, only: [:show, :new, :create]

  before_action :set_caregiver_email, only: [:show, :new, :create]
  before_action :is_authenticated, only: :new
  before_action :is_authenticated_fammember, only: :new

  def index
    if current_user.usertype === "Fammember"
      @transactions = Transaction.all
    end
  end

  def show
  end

  def new
    @transaction = Transaction.new
  end


  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user_id = current_user.id
    @transaction.caregiver_id = @caregiver.id
    @patients = Patient.where(fammember_id: Fammember.find_by(user_id: current_user.id))
    if @transaction.save
      UserMailer.fammember_transaction_email(current_user).deliver
      UserMailer.caregiver_transaction_email(@caregiveremail).deliver
      redirect_to root_path, notice: 'Thank you for booking with us.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    @transaction = Transaction.find(params[:id]).update(transaction_params)
    @transaction2 = Transaction.find(params[:id]).update(pending: false)
    if transaction_params['approved'] == false
      @transaction3 = Transaction.find(params[:id]).update(cancelled: true)  #got error. not working.
    end

    redirect_to caregiver_path(current_user)

  end

  def destroy
    @transaction.destroy
    redirect_to fammember_path, notice: 'Your transaction has been successfully destroyed.'
  end

private

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  def set_caregiver
    @caregiver = Caregiver.find_by(id: params[:caregiver_id])
  end

  def set_caregiver_email
    @caregiveremail = User.find_by(id: @caregiver.user_id)
  end

  def transaction_params
    params.require(:transaction).permit(:start_date, :approved, :patient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caregivers_helper.rb
module CaregiversHelper
end

app/helpers/careseekers_helper.rb
module CareseekersHelper
end

app/helpers/fammembers_helper.rb
module FammembersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/transactions/_form.html.erb
<%= bootstrap_form_for(:transaction, url: caregiver_transactions_path, html: { method: :post }) do |f| %>

  <div>
    Name of requestor: <%= current_user.first_name %> <%= current_user.last_name %>
  </div>

  <div>
    <%= f.collection_select :patient_id, Patient.where(fammember_id: Fammember.find_by(user_id: current_user.id)), :id, :first_name %>
  </div>

  <div>
    Name of caregiver: <%= @caregiver.id %>
  </div>

  <div>
    <%= f.date_field :start_date %>
  </div>

  <div>
    <%= f.submit %>
  </div>

<% end %>

app/views/transactions/edit.html.erb
<h3> List of all previous transactions </h3>


<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name of caregiver</th>
      <th>Family Member</th>
      <th>Start date of booking</th>
      <th>Status</th>
    </tr>
  </thead>

  <tbody>
    <%= bootstrap_form_for @transaction, url: caregiver_transaction_path(:caregiver_id, @transaction.id), html: {method: :patch} do |f| %>
    <td><%= current_user.first_name%><%= current_user.last_name%> </td>
    <td><%= User.find_by(id: @transaction.user_id).first_name%><%= User.find_by(id: @transaction.user_id).last_name%> </td>
    <td><%= f.text_field :start_date, value: @transaction.start_date, :readonly => 'readonly' %></td>
    <td><%= f.collection_radio_buttons :approved , [[true, 'True'] ,[false, 'False']], :first, :last,  {:item_wrapper_class => 'inline'}  %> </td>

  </tbody>

</table>
<%= f.submit %>

  <% end %>

app/views/transactions/index.html.erb
<h1>INDEX PAGE FOR TRANSACTIONS</h1>

app/views/transactions/new.html.erb
<h1>Make a new booking request</h1>

<%= render 'form' %>

app/views/transactions/show.html.erb
<h3> List of all previous transactions </h3>


<table>
  <thead>
    <tr>
      <th>Name of caregiver</th>
      <th>Patient Name</th>
      <th>Start date of booking</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    </tr>
  </tbody>
</table>