config/routes.rb
Rails.application.routes.draw do


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :fammembers do
    resources :patients, only: [:new, :create, :show, :edit, :delete]
    resources :reviews
  end


resources :reviews

  resources :caregivers do
    resources :transactions
    resources :reviews
  end

  get 'edit_transaction' => 'transactions#edit'
  put 'edit_transaction' => 'transactions#update'


  # resources :transactions
  resources :searches


  root 'home#index'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/caregiver.rb
class Caregiver < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :languages
  has_and_belongs_to_many :specialties
  after_initialize :defaultVal

  validates :gender, presence: true
  validates :yearsofexperience, presence: true


  def upload_file
  end

  def defaultVal
    self.certification = false if self.certification.nil?
  end
end

app/models/fammember.rb
class Fammember < ApplicationRecord
  belongs_to :user
  has_many :patients
end

app/models/language.rb
class Language < ApplicationRecord
  has_and_belongs_to_many :caregivers

  validates :sglang, uniqueness: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :fammember

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :owner, foreign_key: "transaction_id", class_name: "Transaction"
end

app/models/search.rb
class Search < ApplicationRecord

    def search_caregivers_attributes
      caregivers = Caregiver.all
      caregivers = caregivers.where("yearsofexperience >= ?", yearsofexperience) if yearsofexperience.present?
      caregivers = caregivers.where("lower(gender) LIKE ?", gender.downcase) if gender.present?
      if self.specialties.present?
        arr = JSON.parse(self.specialties)
        p 'arr contains ...'
        puts arr.length
        if arr.length > 1 # cos there's alaways a blank string being submitted.
          caregiversSpecialty = CaregiversSpecialties.where(specialty_id: arr.map {|x|  x.to_i}).pluck(:caregiver_id)
          p 'caregivers located...? '
          p caregiversSpecialty
          caregivers = caregivers.where(id: caregiversSpecialty)
        end
      end
      if self.languages.present?
        arr = JSON.parse(self.languages)
        if arr.length > 1  # cos there's alaways a blank string being submitted.
          caregiversLanguages = CaregiversLanguages.where(language_id: arr.map {|x|  x.to_i}).pluck(:caregiver_id)
          p 'caregivers located...? '
          p caregiversLanguages
          caregivers = caregivers.where(id: caregiversLanguages)
        end
      end

      return caregivers
    end

end

app/models/specialty.rb
class Specialty < ApplicationRecord
  has_and_belongs_to_many :caregivers

  validates :ability, uniqueness: true


end

app/models/transaction.rb
class Transaction < ApplicationRecord

  belongs_to :user
  belongs_to :caregiver
  has_many :reviews
  belongs_to :patient
  
end

app/models/user.rb
class User < ApplicationRecord
  has_one :fammember, dependent: :destroy
  has_one :caregiver, dependent: :destroy
  has_many :reviews


  before_save {self.email = email.downcase}

  validates :email,
  presence: true,
  uniqueness: {case_sensitive: false},
  format: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :password, length: {in: 8..72}, on: :create

  validates :contact, length: {is: 8},
  presence: true

  has_secure_password

  def self.find_and_authenticate(params)
    User.find_by_email(params[:email]).try(:authenticate, params[:password])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/caregivers_helper.rb
module CaregiversHelper
end

app/helpers/careseekers_helper.rb
module CareseekersHelper
end

app/helpers/fammembers_helper.rb
module FammembersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>

      <% if !current_user %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Start using", new_fammember_path %></li>
          <li><%= link_to "Become our caregiver", caregivers_path %></li>
          <li><%= link_to "Search", new_search_path %></li>
          <li><%= link_to "Sign In", login_path %></li>
        </ul>

      <% elsif current_user.usertype == 'Caregiver'%>

        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Information", url: '#' %></li>
          <li><%= link_to "Profile", caregiver_path(current_user) %></li>
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
        </ul>

      <% elsif current_user.usertype == 'Fammember'%>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Search for caregiver", new_search_path %></li>
          <li><%= link_to "Profile", fammember_path(current_user) %></li>
          <li><%= link_to "Review", reviews_path %></li>
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
        </ul>

    <% end %>


    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Silverhomecare</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render "partials/flash" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/home.html.erb
<h1>About Us</h1>

app/views/partials/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
<% end %>